spring:
  datasource:
    url: jdbc:mysql://localhost:3306/event_Api?createDatabaseIfNotExist = true
    username: root
    password: 20051216

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
